// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srapqeeddrxzpocvheap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyYXBxZWVkZHJ4enBvY3ZoZWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4OTE1OTksImV4cCI6MjA1MjQ2NzU5OX0.qsa1ES3WRokAdnVSH6Rf540H9OJ4xPDhTrrndP7X0JE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);